/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArRouteImport } from './routes/ar'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ArIndexRouteImport } from './routes/ar.index'
import { Route as ArAboutRouteImport } from './routes/ar.about'
import { Route as ArCaseStudiesRouteImport } from './routes/ar.case-studies'
import { Route as ArContactRouteImport } from './routes/ar.contact'
import { Route as ArProcessRouteImport } from './routes/ar.process'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ArServicesIndexRouteImport } from './routes/ar.services.index'
import { Route as ArServicesSlugRouteImport } from './routes/ar.services.$slug'
import { Route as ArWorkIndexRouteImport } from './routes/ar.work.index'
import { Route as ArWorkSlugRouteImport } from './routes/ar.work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArRoute,
} as any)
const ArAboutRoute = ArAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ArRoute,
} as any)
const ArCaseStudiesRoute = ArCaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => ArRoute,
} as any)
const ArContactRoute = ArContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ArRoute,
} as any)
const ArProcessRoute = ArProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => ArRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArServicesIndexRoute = ArServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => ArRoute,
} as any)
const ArServicesSlugRoute = ArServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => ArRoute,
} as any)
const ArWorkIndexRoute = ArWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => ArRoute,
} as any)
const ArWorkSlugRoute = ArWorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => ArRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ar': typeof ArRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/case-studies': typeof ArCaseStudiesRoute
  '/ar/contact': typeof ArContactRoute
  '/ar/process': typeof ArProcessRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/ar/': typeof ArIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/ar/services/$slug': typeof ArServicesSlugRoute
  '/ar/work/$slug': typeof ArWorkSlugRoute
  '/ar/services/': typeof ArServicesIndexRoute
  '/ar/work/': typeof ArWorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/case-studies': typeof ArCaseStudiesRoute
  '/ar/contact': typeof ArContactRoute
  '/ar/process': typeof ArProcessRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/ar': typeof ArIndexRoute
  '/services': typeof ServicesIndexRoute
  '/work': typeof WorkIndexRoute
  '/ar/services/$slug': typeof ArServicesSlugRoute
  '/ar/work/$slug': typeof ArWorkSlugRoute
  '/ar/services': typeof ArServicesIndexRoute
  '/ar/work': typeof ArWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ar': typeof ArRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/case-studies': typeof ArCaseStudiesRoute
  '/ar/contact': typeof ArContactRoute
  '/ar/process': typeof ArProcessRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/ar/': typeof ArIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/ar/services/$slug': typeof ArServicesSlugRoute
  '/ar/work/$slug': typeof ArWorkSlugRoute
  '/ar/services/': typeof ArServicesIndexRoute
  '/ar/work/': typeof ArWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ar'
    | '/case-studies'
    | '/contact'
    | '/process'
    | '/sitemap.xml'
    | '/ar/about'
    | '/ar/case-studies'
    | '/ar/contact'
    | '/ar/process'
    | '/services/$slug'
    | '/work/$slug'
    | '/ar/'
    | '/services/'
    | '/work/'
    | '/ar/services/$slug'
    | '/ar/work/$slug'
    | '/ar/services/'
    | '/ar/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/process'
    | '/sitemap.xml'
    | '/ar/about'
    | '/ar/case-studies'
    | '/ar/contact'
    | '/ar/process'
    | '/services/$slug'
    | '/work/$slug'
    | '/ar'
    | '/services'
    | '/work'
    | '/ar/services/$slug'
    | '/ar/work/$slug'
    | '/ar/services'
    | '/ar/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ar'
    | '/case-studies'
    | '/contact'
    | '/process'
    | '/sitemap.xml'
    | '/ar/about'
    | '/ar/case-studies'
    | '/ar/contact'
    | '/ar/process'
    | '/services/$slug'
    | '/work/$slug'
    | '/ar/'
    | '/services/'
    | '/work/'
    | '/ar/services/$slug'
    | '/ar/work/$slug'
    | '/ar/services/'
    | '/ar/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArRoute: typeof ArRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  ProcessRoute: typeof ProcessRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/': {
      id: '/ar/'
      path: '/'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/about': {
      id: '/ar/about'
      path: '/about'
      fullPath: '/ar/about'
      preLoaderRoute: typeof ArAboutRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/case-studies': {
      id: '/ar/case-studies'
      path: '/case-studies'
      fullPath: '/ar/case-studies'
      preLoaderRoute: typeof ArCaseStudiesRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/contact': {
      id: '/ar/contact'
      path: '/contact'
      fullPath: '/ar/contact'
      preLoaderRoute: typeof ArContactRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/process': {
      id: '/ar/process'
      path: '/process'
      fullPath: '/ar/process'
      preLoaderRoute: typeof ArProcessRouteImport
      parentRoute: typeof ArRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/services/': {
      id: '/ar/services/'
      path: '/services'
      fullPath: '/ar/services/'
      preLoaderRoute: typeof ArServicesIndexRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/services/$slug': {
      id: '/ar/services/$slug'
      path: '/services/$slug'
      fullPath: '/ar/services/$slug'
      preLoaderRoute: typeof ArServicesSlugRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/work/': {
      id: '/ar/work/'
      path: '/work'
      fullPath: '/ar/work/'
      preLoaderRoute: typeof ArWorkIndexRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/work/$slug': {
      id: '/ar/work/$slug'
      path: '/work/$slug'
      fullPath: '/ar/work/$slug'
      preLoaderRoute: typeof ArWorkSlugRouteImport
      parentRoute: typeof ArRoute
    }
  }
}

interface ArRouteChildren {
  ArAboutRoute: typeof ArAboutRoute
  ArCaseStudiesRoute: typeof ArCaseStudiesRoute
  ArContactRoute: typeof ArContactRoute
  ArProcessRoute: typeof ArProcessRoute
  ArIndexRoute: typeof ArIndexRoute
  ArServicesSlugRoute: typeof ArServicesSlugRoute
  ArWorkSlugRoute: typeof ArWorkSlugRoute
  ArServicesIndexRoute: typeof ArServicesIndexRoute
  ArWorkIndexRoute: typeof ArWorkIndexRoute
}

const ArRouteChildren: ArRouteChildren = {
  ArAboutRoute: ArAboutRoute,
  ArCaseStudiesRoute: ArCaseStudiesRoute,
  ArContactRoute: ArContactRoute,
  ArProcessRoute: ArProcessRoute,
  ArIndexRoute: ArIndexRoute,
  ArServicesSlugRoute: ArServicesSlugRoute,
  ArWorkSlugRoute: ArWorkSlugRoute,
  ArServicesIndexRoute: ArServicesIndexRoute,
  ArWorkIndexRoute: ArWorkIndexRoute,
}

const ArRouteWithChildren = ArRoute._addFileChildren(ArRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArRoute: ArRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  ProcessRoute: ProcessRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
